NASAAPPS/projectsite/allysocials/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from allysocials import views

app_name = 'allysocials'
urlpatterns = [
    url(r"blogmainpage/$",views.showallysocials,name='blog_main_page'),
    url(r"aboutsocials/$",views.showabtallysocials,name='blog_about'),
    ]

NASAAPPS/projectsite/projectsite/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^sitepages/',include('sitepages.urls',namespace='sitepages')),
    url(r'^sitepages/',include('django.contrib.auth.urls')),
    url(r'^allysocials/',include('allysocials.urls',namespace='allysocials')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

NASAAPPS/projectsite/sitepages/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
#this file already takes care of login and logout views.
from . import views

app_name = 'sitepages'

urlpatterns = [
        url(r"login/$",auth_views.LoginView.as_view(template_name='sitepages/login.html'),name='login'),
        url(r"logout/$",auth_views.LogoutView.as_view(),name='logout'),
        url(r"signupindividual/$",views.IndividualSignUpForm.as_view(),name='signupindividual'),
        url(r"signupcorporate/$",views.CorporateSignUpForm.as_view(),name='signupcorporate'),
        url(r"signupchoice/$",views.SignUpChoice,name='signupchoice'),
        url(r"ally_assess/$",views.AllyAssessPage,name='allyassess'),
        url(r"personalinfocard/$",views.save,name='cardinfoform'),
        url(r"personalinfovalid/$",views.personalinfovalid,name='cardinfovalid'),
        url(r"cardview/$",views.ViewCards,name='viewcards'), 
        path("cardcompleteinfo/<card_id>",views.ShowMoreInfo,name='completeinfo'), 
    ]
#After making this we need to connect our sitepages to the full project using views and url.
#We will add it the main urls.py

NASAAPPS/projectsite/allysocials/models.py
from django.db import models

# Create your models here.

NASAAPPS/projectsite/sitepages/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.utils.html import escape, mark_safe
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_resized import ResizedImageField


class User(AbstractUser):
    is_corporate = models.BooleanField(default=False)
    is_individual = models.BooleanField(default=False)



class Individual(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField()
    image = ResizedImageField(size=[500, 300], upload_to='images/', blank=True, null=True,quality=100)
    instagram_link = models.CharField(max_length=100)
    linkedin_link = models.CharField(max_length=100)
    skills = models.TextField()
    education = models.TextField()
    work_exp = models.CharField(max_length=200)

    class Meta:
        db_table = 'Individual'
    

    def __str__(self):
        return self.user.username

NASAAPPS/projectsite/sitepages/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django import forms
from django.forms.utils import ValidationError
from sitepages.models import (User,Individual)


class CorporateSignUp(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ('username','email','password1','password2')
        model = User

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Company Email Address'

    def save(self,commit=True):
        user=super().save(commit=False)
        user.is_corporate = True
        if commit:
            user.save()

        return user




class IndividualSignUp(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ('username','email','password1','password2')
        model= User


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_individual = True
        user.save()
        individual = Individual.objects.create(user=user)

        return user



class CardInfoForm(forms.ModelForm):

    class Meta:
        model = Individual
        fields = ['first_name','last_name','bio','image','instagram_link','linkedin_link','skills','education','work_exp']

NASAAPPS/projectsite/allysocials/views.py
from django.shortcuts import render

# Create your views here.
def showallysocials(request):
    return render(request,'allysocials/index.html')


def showabtallysocials(request):
    return render(request,'allysocials/blog-single.html')

NASAAPPS/projectsite/projectsite/views.py
#This is to connect the base and index html to the main site.

from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'


class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'
    
    

NASAAPPS/projectsite/sitepages/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout
from django.views.generic import CreateView
from django.urls import reverse_lazy
from sitepages.forms import CorporateSignUp,IndividualSignUp,CardInfoForm
from sitepages.models import User,Individual
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your views here.
class CorporateSignUpForm(CreateView):
    model = User
    form_class = CorporateSignUp
    template_name = 'sitepages/signup.html'
    

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'corporate'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('sitepages/login')


class IndividualSignUpForm(CreateView):
    model = User
    form_class = IndividualSignUp
    template_name = 'sitepages/signup.html'
    

    def get_context_data(self,**kwargs):
        kwargs['user_type'] = 'individual'
        return super().get_context_data(**kwargs)

    def form_valid(self,form):
        user = form.save()
        return redirect('sitepages/login')

def save(request):
    
    if request.method == 'POST':
        obj = CardInfoForm(request.POST,request.FILES)
        try:
            if obj.is_valid():          
                form = obj.save(commit=False)
                form.user = User.objects.get(id=request.user.id)
                form.save()
                return render(request,'sitepages/valid.html')
        except:
            return redirect('')
    else:
        obj = CardInfoForm()
    return render(request,'sitepages/personalinfoform.html',{'form':obj})
                
def personalinfovalid(request):
    return render(request,'sitepages/valid.html')


def SignUpChoice(request):
     return render(request,'sitepages/first.html')


def AllyAssessPage(request):
    return render(request,'sitepages/allyassess.html')


def ViewCards(request):
    all_info = Individual.objects.all()
    return render(request,'sitepages/profilecard.html',{'all_cards':all_info})


#TO LOOK AT A SPECIFIC CARD.
def ShowMoreInfo(request,card_id):
    specific_info = Individual.objects.get(pk=card_id)
    return render(request,'sitepages/showcardinfo.html',{'info':specific_info})

NASAAPPS/projectsite/sitepages/templates/sitepages/allyassess.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% extends 'base.html' %} {% load static %} {% block content %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ally Assess</title>
    <link
      rel="stylesheet"
      href="{% static './projectsite/css/allyassess.css' %} "
    />
  </head>
  <body>
    <div class="container">
      <iframe
        src="https://docs.google.com/forms/d/e/1FAIpQLScRG1QYtMdVXsJ1e_y20_ZjvIWi8viUXOsq_qi-y4kjMlA69Q/viewform?embedded=true"
        class="form"
        frameborder="0"
        marginheight="0"
        marginwidth="0"
        >Loading…</iframe
      >
    </div>
  </body>
</html>

{% endblock %}

NASAAPPS/projectsite/sitepages/templates/sitepages/first.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% extends 'base.html' %} {% load bootstrap4 %} {% block content %}
  {% load static %}

  <head>
	  <link rel="stylesheet" href="{% static './projectsite/css/signup.css' %}">
  </head>

  <body>
        
    <div>
    <div class='jumbotron'>
      <div class="container">
        <h1 class="display-3">Welcome to the Sign-Up Page</h1>
        <p>
          Ally Pride Fashion🌈 is an open platform for making the LGBTQ+ community grow larger and stronger in the Fashion industry.
          Corporate functionality enables professionals to look at portfolio cards of LGBT individuals and select the most appropriate candidate.
          As an Individual you get the oppurtunity to showcase your skills and create a card which can be viewed by only professionals.
        </p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-6">
          <h2>Individual Sign-up</h2>
          <p>
            If you are an individual looking forward to join our initiative,
            join from here.
          </p>
          <p>
            <a class="btn btn-secondary" href="{% url 'sitepages:signupindividual' %}" role="button"
              >Click to SignUp &raquo;</a
            >
          </p>
        </div>
        <div class="col-md-6">
          <h2>Corporate Signup</h2>
          <p>
            If you are an organization or a company, connect with us from here.
          </p>
          <p>
            <a class="btn btn-secondary" href="{% url 'sitepages:signupcorporate' %}" role="button"
              >Click to SignUp &raquo;</a
            >
          </p>
        </div>
      </div>

      <hr />
    </div>
  </div>
    <!-- /container -->
</body>
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script>
    window.jQuery ||
      document.write(
        '<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>'
      );
  </script>
  <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
</html>

{% endblock %}

NASAAPPS/projectsite/sitepages/templates/sitepages/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class='container'>
	<h1>Log In</h1>
	<form method="POST">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button type="submit" class ="btn btn-default">Log In</button>
		{% endbuttons %}

	</form>
</div>
{% endblock %}

NASAAPPS/projectsite/sitepages/templates/sitepages/personalinfoform.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <div class='container'>
    <h1>Input Your Information for the form</h1>
    <form method='POST' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      </br>
      {% buttons %}
        <button type="submit" class ="btn btn-default">Sumbit</button>
      {% endbuttons %}
    </form>
</div>
{% endblock %}

NASAAPPS/projectsite/sitepages/templates/sitepages/profilecard.html
<!DOCTYPE html>
{% load static %} 

<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="apple-mobile-web-app-title" />
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500&display=swap" rel="stylesheet">
    <title>Ally Profiles</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css"
    />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'profilecard/css/style.css' %}" />

    <script>
      window.console = window.console || function (t) {};
    </script>

    <script>
      if (document.location.search.match(/type=embed/gi)) {
        window.parent.postMessage("resize", "*");
      }
    </script>
  </head>

  <body translate="no" style="background-image:url('https://image.freepik.com/free-photo/lgbt-background-concept-top-view-with-copy-spaces_136346-2960.jpg')">
    <nav class="navbar  mynav" role="navigation" id="navbar">
      <a class="navbar-brand mynav" href="{% url 'home' %}">Home Page</a>
    </nav>
    <form action="" method="post">
      <div class="tinder">
        <div class="tinder--status">
          <i class="fa fa-remove"></i>
          <i class="fa fa-heart"></i>
        </div>
        
        <div class="tinder--cards">
          {% csrf_token %}
          {% for card in all_cards %}
            <div class="tinder--card">
              <img src="{{card.image.url}}" />
              <h3>{{ card.first_name }}</h3>
              <p style="text-align: left">Bio:{{card.bio}}</br>Skills:{{card.skills}}</br>Instagram Link: {{ card.instagram_link }}</p>
              <button class="profile" style="margin-top: 5%; " formaction="{% url 'sitepages:completeinfo' card.user_id %}" type="submit">More Info</button>
            </div>
          {% endfor %}
        </div>
        
        <div class="tinder--buttons">
          <button id="nope"><i class="fa fa-remove"></i></button>
          <button id="love"><i class="fa fa-heart"></i></button>
        </div>
      </div>
    </form>
    <script src="https://static.codepen.io/assets/common/stopExecutionOnTimeout-157cd5b220a5c80d4ff8e0e70ac069bffd87a61252088146915e8726e5d9f147.js"></script>

    <script src="https://hammerjs.github.io/dist/hammer.min.js"></script>

    <script id="rendered-js" src="{% static 'profilecard/js/style.js' %}"></script>
  </body>
<style>
  .profile {
  display: inline-block;
  border-radius: 20px;
  border: none;
  background-color: #87C9FF;
  text-align: center;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.profile span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.profile span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.profile:hover span {
  padding-right: 25px;
}

.profile:hover span:after {
  opacity: 1;
  right: 0;
}
</style>
</html>

NASAAPPS/projectsite/sitepages/templates/sitepages/showcardinfo.html
{% extends 'base.html' %}

{% block content %}
    <div class='container'>
        <form action='' method="POST">
            {% csrf_token %}
            <img src={{ info.image.url }}></img>
            </br>
            </br>
            <p>Name: {{ info.first_name }} {{ info.last_name }}</p>
            </br>
            <p>Bio: {{ info.bio }}</p>
            <p>Instagram Link: <a href={{ info.instagram_link }}>{{ info.instagram_link }}</a></p>
            <p>Linkedin Link: <a href={{ info.linked_link }}>{{ info.linked_link }}</a></p>
            <p>Skills: {{ info.skills }}</p>
            <p>Education: {{ info.education }}</p>
            <p>Work Experience: {{ info.work_exp }}</p>
        </form>
    </div>
{% endblock %}

NASAAPPS/projectsite/sitepages/templates/sitepages/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class='container'>
	<h1>Sign Up</h1>
	<form method="POST">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button type="submit" class ="btn btn-default">Sign Up</button>
		{% endbuttons %}
	</form>
</div>
{% endblock %}

NASAAPPS/projectsite/sitepages/templates/sitepages/valid.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
    {% csrf_token %}
    <h1>Form has been updated.</h1>
</div>
{% endblock %}

NASAAPPS/projectsite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <title>Team Ally</title>
    <link
      rel="icon"
      type="image/png"
      href="/media/images/ally-logo-white.png"
    />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />

    <!-- Optional theme -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous"
    />

    <!-- Latest compiled and minified JavaScript -->
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"
    ></script>

    <link
      href="https://fonts.googleapis.com/css?family=Montserrat"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{% static 'projectsite/css/master.css'%}" />
  </head>

  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark bg-dark static-top"
      role="navigation"
      id="navbar"
    >
      {% csrf_token %}
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img
            src="/media/images/ally-logo-white.png"
            alt="HomePage"
            class="nav-logo"
          />
        </a>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %} {% if user.is_individual %}
          <li>
            <a href="https://ally.trydiscourse.com/" class="btn btn-simple"
              >Ally Discourse</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:allyassess' %}" class="btn btn-simple"
              >Ally Bais Assessment</a
            >
          </li>
          <li>
            <a
              href="{% url 'allysocials:blog_main_page' %}"
              class="btn btn-simple"
              >Ally Socials</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:cardinfoform'  %}" class="btn btn-simple"
              >Create Card</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:logout' %}" class="btn btn-simple"
              >Log out</a
            >
          </li>
          {% elif user.is_corporate %}
          <li>
            <a href="https://ally.trydiscourse.com/" class="btn btn-simple"
              >Ally Discourse</a
            >
          </li>

          <li>
            <a href="{% url 'sitepages:allyassess' %}" class="btn btn-simple"
              >Ally Bias Assessment</a
            >
          </li>
          <li>
            <a
              href="{% url 'allysocials:blog_main_page' %}"
              class="btn btn-simple"
              >Ally Socials</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:viewcards' %}" class="btn btn-simple"
              >View Cards</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:logout' %}" class="btn btn-simple"
              >Log out</a
            >
          </li>
          {% endif %} {% else %}
          <li>
            <a href="https://ally.trydiscourse.com/" class="btn btn-simple"
              >Ally Discourse</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:allyassess' %}" class="btn btn-simple"
              >Ally Bias Assessment</a
            >
          </li>
          <li>
            <a
              href="{% url 'allysocials:blog_main_page' %}"
              class="btn btn-simple"
              >Ally socials</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:login' %}" class="btn btn-simple"
              >Log in</a
            >
          </li>
          <li>
            <a href="{% url 'sitepages:signupchoice' %}" class="btn btn-simple"
              >Sign up</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <canvas id="canvas" style="position: absolute"></canvas>
    <div
      class="container mycontent"
      style="position: absolute; font-size: 2.5rem; text-align: justify"
    >
      {% block content %} {% endblock %}
    </div>

    <span id="note"></span>
  </body>
  <script
    type="text/javascript"
    src="{% static 'projectsite/js/master.js' %}"
  ></script>
</html>

NASAAPPS/projectsite/templates/index.html
{% extends "base.html" %} {% load static %} {% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  {% block content %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'projectsite/css/master.css' %}" />
    <link rel="stylesheet" href="{% static 'projectsite/css/home.css' %}" />
  </head>
  <body>
    <div class="head1">
      <h1>Welcome to Ally</h1>
      <br />
    </div>
    <div class="row body1">
      <div class="col-lg-9">
        <p>
          Breaking the barriers, Coming together as one. “Ally” is a website
          platform to connect,and be educated about inequality that can impact
          millions of lives. “Ally Social” displays the current situation of
          LGBT and Black lives as stories and podcasts, “Ally Discourse”
          provides a safe forum where people can connect, share problems,and
          inspire. “Ally Pride Fashion” is a novel and innovative approach that
          gives the LGBT an open platform to connect with professionals and
          companies, to progress in their careers and leave a mark on the
          Fashion Industry.

          <br />
          <br />
          “Ally Bias Assessment” allows reflecting on viewpoints as an essential
          way to start realising and breaking down biases and harmful
          perceptions.
        </p>
      </div>
      <div class="col-lg-3">
        <img src="/media/images/NASA logo.png" alt="" id="nasalogo" />
      </div>
    </div>

    <br /><br /><br />
    <hr />
    <br /><br />

    <div class="container teamsection">
      <div class="row">
        <div class="heading-title text-center">
          <h3 class="text-uppercase">Our Team</h3>
          <p class="p-top-30 half-txt">Meet the minds behind this project.</p>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="team-member">
            <div class="team-img">
              <img
                src="/media/images/Avi.jpg"
                alt="team member"
                class="img-responsive teamimg"
              />
            </div>
            <div class="team-hover">
              <div class="desk">
                <h4>Hello World</h4>
                <p>I love to introduce myself as a hardcore Web Designer.</p>
              </div>
              <div class="s-link">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
              </div>
            </div>
          </div>
          <div class="team-title">
            <h5>Avi Gautam</h5>
            <span></span>
          </div>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="team-member">
            <div class="team-img">
              <img
                src="/media/images/Stuti.jpg"
                alt="team member"
                class="img-responsive teamimg"
              />
            </div>
            <div class="team-hover">
              <div class="desk">
                <h4>Hi There !</h4>
                <p>I love to introduce myself as a hardcore Web Designer.</p>
              </div>
              <div class="s-link">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
              </div>
            </div>
          </div>
          <div class="team-title">
            <h5>Stuti Sehgal</h5>
            <span></span>
          </div>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="team-member">
            <div class="team-img">
              <img
                src="/media/images/Kavya.jpeg"
                alt="team member"
                class="img-responsive teamimg"
              />
            </div>
            <div class="team-hover">
              <div class="desk">
                <h4>I love to design</h4>
                <p>I love to introduce myself as a hardcore Web Designer.</p>
              </div>
              <div class="s-link">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
              </div>
            </div>
          </div>
          <div class="team-title">
            <h5>Kavya Priya</h5>
            <span></span>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 col-sm-6" style="padding-left: 15%">
            <div class="team-member">
              <div class="team-img">
                <img
                  src="/media/images/Hritik.jpg"
                  alt="team member"
                  class="img-responsive teamimg"
                />
              </div>
              <div class="team-hover">
                <div class="desk">
                  <h4>Hello World</h4>
                  <p>I love to introduce myself as a hardcore Web Designer.</p>
                </div>
                <div class="s-link">
                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-google-plus"></i></a>
                </div>
              </div>
            </div>
            <div class="team-title">
              <h5>Hritik Bhandari</h5>
              <span></span>
            </div>
          </div>

          <div class="col-md-6 col-sm-6" style="padding-left: 5%">
            <div class="team-member">
              <div class="team-img">
                <img
                  src="/media/images/Shubhangi.jpeg"
                  alt="team member"
                  class="img-responsive teamimg"
                />
              </div>
              <div class="team-hover">
                <div class="desk">
                  <h4>Hello World</h4>
                  <p>I love to introduce myself as a hardcore Web Designer.</p>
                </div>
                <div class="s-link">
                  <a href="#"><i class="fa fa-facebook"></i></a>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                  <a href="#"><i class="fa fa-google-plus"></i></a>
                </div>
              </div>
            </div>
            <div class="team-title">
              <h5>Shubhangi Soni</h5>
              <span></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br /><br /><br />
    <hr />
    <br />
    <br />
    <div class="heading-title text-center">
      <h2>Timeline of the project</h2>
      <br />
      <div class="timelineimg">
        <img src="/media/images/timeline.png" style="max-width: 95%" />
      </div>
    </div>

    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <script>
      window.watsonAssistantChatOptions = {
        integrationID: "f62fbcbf-6ef4-4f7a-935b-d93e08a063d8", // The ID of this integration.
        region: "eu-gb", // The region your integration is hosted in.
        serviceInstanceID: "a564abd8-2eed-4afc-9199-20b170e01a09", // The ID of your service instance.
        onLoad: function (instance) {
          instance.render();
        },
      };
      setTimeout(function () {
        const t = document.createElement("script");
        t.src =
          "https://web-chat.global.assistant.watson.appdomain.cloud/loadWatsonAssistantChat.js";
        document.head.appendChild(t);
      });
    </script>
  </body>
  {% endblock %}
</html>

NASAAPPS/projectsite/templates/test.html
{% extends "base.html" %}
{% block content %}
	{% csrf_token %}
	<h1>You are now logged in!</h1>

{% endblock %}

NASAAPPS/projectsite/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}